import { Client, type IMessage } from '@stomp/stompjs';
import type { Note, SyncAckResponse, SyncChangeEvent, SyncMutationRequest, SyncResyncResponse, DeviceActivity } from '@syncnotes/types';
import { resolveLwwConflict, generateClientMutationId, getOrCreateDeviceId, getReadableDeviceName } from '@syncnotes/utils';
import { db } from './db';

const API_BASE = (import.meta.env.VITE_API_BASE_URL as string) || 'http://localhost:8080';
const WS_BASE = (import.meta.env.VITE_WS_BASE_URL as string) || 'ws://localhost:8080/ws-sync';

export type SyncState = 'CONNECTED' | 'CONNECTING' | 'OFFLINE' | 'RECONNECTING';

export class SyncEngine {
  private stompClient: Client | null = null;
  private token: string | null = null;
  private deviceId: string;
  private isProcessingOutbox = false;
  private state: SyncState = 'OFFLINE';

  private onStateChangeListeners = new Set<(state: SyncState) => void>();
  private onRemoteUpdateListeners = new Set<(note: Note, originDeviceType: 'Windows' | 'iPhone' | 'Device') => void>();
  private onDeviceActivityListeners = new Set<(activities: DeviceActivity[]) => void>();
  private recentActivities: DeviceActivity[] = [];

  constructor() {
    this.deviceId = getOrCreateDeviceId('syncnotes_desktop_dev_id',
      () => localStorage.getItem('syncnotes_device_id'),
      (id) => localStorage.setItem('syncnotes_device_id', id)
    );
  }

  public setToken(token: string | null) {
    this.token = token;
    if (token) {
      this.connect();
    } else {
      this.disconnect();
    }
  }

  public getDeviceId(): string {
    return this.deviceId;
  }

  public subscribeState(listener: (state: SyncState) => void) {
    this.onStateChangeListeners.add(listener);
    listener(this.state);
    return () => this.onStateChangeListeners.delete(listener);
  }

  public subscribeRemoteUpdate(listener: (note: Note, originDeviceType: 'Windows' | 'iPhone' | 'Device') => void) {
    this.onRemoteUpdateListeners.add(listener);
    return () => this.onRemoteUpdateListeners.delete(listener);
  }

  public subscribeDeviceActivity(listener: (activities: DeviceActivity[]) => void) {
    this.onDeviceActivityListeners.add(listener);
    listener(this.recentActivities);
    return () => this.onDeviceActivityListeners.delete(listener);
  }


  private setState(newState: SyncState) {
    this.state = newState;
    this.onStateChangeListeners.forEach(l => l(newState));
  }

  public connect() {
    if (!this.token) return;
    if (this.stompClient && this.stompClient.active) return;

    this.setState('CONNECTING');

    this.stompClient = new Client({
      brokerURL: WS_BASE,
      connectHeaders: {
        Authorization: `Bearer ${this.token}`,
      },
      reconnectDelay: 3000,
      heartbeatIncoming: 10000,
      heartbeatOutgoing: 10000,
      onConnect: () => {
        this.setState('CONNECTED');
        this.subscribeChannels();
        this.performCursorCatchUp();
        this.flushOutbox();
      },
      onDisconnect: () => {
        this.setState('OFFLINE');
      },
      onStompError: (frame) => {
        console.error('STOMP Error:', frame.headers['message']);
        this.setState('RECONNECTING');
      },
      onWebSocketClose: () => {
        this.setState('OFFLINE');
      },
    });

    this.stompClient.activate();
  }

  public disconnect() {
    if (this.stompClient) {
      this.stompClient.deactivate();
      this.stompClient = null;
    }
    this.setState('OFFLINE');
  }

  private subscribeChannels() {
    if (!this.stompClient) return;

    // Subscribe to user-scoped realtime change events
    this.stompClient.subscribe('/user/queue/sync.events', (msg: IMessage) => {
      try {
        const event: SyncChangeEvent = JSON.parse(msg.body);
        this.handleIncomingChangeEvent(event);
      } catch (err) {
        console.error('Failed parsing sync event', err);
      }
    });

    // Subscribe to mutation acknowledgements
    this.stompClient.subscribe('/user/queue/sync.ack', (msg: IMessage) => {
      try {
        const ack: SyncAckResponse = JSON.parse(msg.body);
        this.handleSyncAck(ack);
      } catch (err) {
        console.error('Failed parsing sync ack', err);
      }
    });
  }

  private async handleIncomingChangeEvent(event: SyncChangeEvent) {
    if (event.originDeviceId === this.deviceId) {
      // Ignore echoed events generated by this device
      return;
    }

    if (event.entityType === 'NOTE') {
      const incomingNote = event.payload as Note;
      const existing = await db.notes.get(incomingNote.id);
      const originDeviceType = getReadableDeviceName(event.originDeviceId);

      if (!existing) {
        await db.notes.put(incomingNote);
        this.notifyRemoteUpdate(incomingNote, originDeviceType, event.operation, event.originDeviceId);
      } else {
        const lww = resolveLwwConflict(
          incomingNote.updatedAt,
          event.originDeviceId,
          existing.updatedAt,
          existing.clientMutationId || ''
        );

        if (lww.clientWins || event.operation === 'DELETE') {
          await db.notes.put(incomingNote);
          this.notifyRemoteUpdate(incomingNote, originDeviceType, event.operation, event.originDeviceId);
        }
      }

      // Update cursor
      await db.meta.put({ key: 'last_revision', value: event.revisionId });
    }
  }

  private async handleSyncAck(ack: SyncAckResponse) {
    // Remove completed item from local outbox
    await db.outbox.where('mutation.clientMutationId').equals(ack.clientMutationId).delete();

    if (ack.status === 'CONFLICT_LWW_LOST' && ack.authoritativeNote) {
      await db.notes.put(ack.authoritativeNote);
      this.notifyRemoteUpdate(ack.authoritativeNote, 'Device', 'UPDATE', 'server');
    }
  }

  private notifyRemoteUpdate(
    note: Note,
    originDeviceType: 'Windows' | 'iPhone' | 'Device' = 'Device',
    operation: 'CREATE' | 'UPDATE' | 'DELETE' = 'UPDATE',
    originDeviceId: string = ''
  ) {
    const activity: DeviceActivity = {
      id: generateClientMutationId(),
      deviceId: originDeviceId || originDeviceType,
      deviceType: originDeviceType,
      operation,
      noteId: note.id,
      noteTitle: note.title || 'Untitled Note',
      timestamp: new Date().toISOString(),
    };

    this.recentActivities = [activity, ...this.recentActivities.slice(0, 19)];
    this.onDeviceActivityListeners.forEach(l => l(this.recentActivities));
    this.onRemoteUpdateListeners.forEach(l => l(note, originDeviceType));
  }


  /**
   * Local-First Mutation Write:
   * Writes edit immediately to IndexedDB and enqueues to Outbox
   */
  public async queueMutation(
    entityId: string,
    operation: 'CREATE' | 'UPDATE' | 'DELETE',
    payload: Partial<Note>,
    baseVersion: number = 1
  ): Promise<Note> {
    const nowIso = new Date().toISOString();
    const mutationId = generateClientMutationId();

    const existing = await db.notes.get(entityId);

    const noteToSave: Note = {
      id: entityId,
      userId: existing?.userId || '',
      title: payload.title !== undefined ? payload.title : existing?.title || '',
      content: payload.content !== undefined ? payload.content : existing?.content || '',
      pinned: payload.pinned !== undefined ? payload.pinned : existing?.pinned || false,
      archived: payload.archived !== undefined ? payload.archived : existing?.archived || false,
      deleted: operation === 'DELETE' || payload.deleted || false,
      version: existing ? existing.version + 1 : baseVersion,
      createdAt: existing?.createdAt || nowIso,
      updatedAt: nowIso,
      deviceId: this.deviceId,
      clientMutationId: mutationId,
    };

    // 1. Optimistic local update
    await db.notes.put(noteToSave);

    // 2. Queue into persistent outbox
    const mutationReq: SyncMutationRequest = {
      clientMutationId: mutationId,
      deviceId: this.deviceId,
      entityType: 'NOTE',
      entityId,
      operation,
      baseVersion,
      payload: {
        id: noteToSave.id,
        title: noteToSave.title,
        content: noteToSave.content,
        pinned: noteToSave.pinned,
        archived: noteToSave.archived,
        deleted: noteToSave.deleted,
        deviceId: this.deviceId,
        clientMutationId: mutationId,
      },
      clientTimestamp: nowIso,
    };

    await db.outbox.put({
      id: mutationId,
      mutation: mutationReq,
      createdAt: Date.now(),
      retryCount: 0,
    });

    // 3. Attempt immediate transmission
    this.flushOutbox();

    return noteToSave;
  }

  public async flushOutbox() {
    if (this.isProcessingOutbox || !this.stompClient || !this.stompClient.connected) return;
    this.isProcessingOutbox = true;

    try {
      const items = await db.outbox.orderBy('createdAt').toArray();
      for (const item of items) {
        if (!this.stompClient || !this.stompClient.connected) break;
        this.stompClient.publish({
          destination: '/app/sync.mutate',
          body: JSON.stringify(item.mutation),
        });
      }
    } catch (err) {
      console.error('Outbox flush error', err);
    } finally {
      this.isProcessingOutbox = false;
    }
  }

  public async performCursorCatchUp() {
    if (!this.token) return;
    try {
      const meta = await db.meta.get('last_revision');
      const cursor = meta ? meta.value : 0;

      const res = await fetch(`${API_BASE}/api/sync/changes?cursor=${cursor}`, {
        headers: {
          Authorization: `Bearer ${this.token}`,
        },
      });

      if (res.ok) {
        const data: SyncResyncResponse = await res.json();
        if (data.requiresSnapshot) {
          await this.fetchAndApplyFullSnapshot();
        } else {
          for (const change of data.changes) {
            await this.handleIncomingChangeEvent(change);
          }
          if (data.latestRevision) {
            await db.meta.put({ key: 'last_revision', value: data.latestRevision });
          }
        }
      }
    } catch (err) {
      console.error('Cursor catch-up error', err);
    }
  }

  public async fetchAndApplyFullSnapshot() {
    if (!this.token) return;
    try {
      const res = await fetch(`${API_BASE}/api/sync/snapshot`, {
        headers: {
          Authorization: `Bearer ${this.token}`,
        },
      });

      if (res.ok) {
        const data: SyncResyncResponse = await res.json();
        if (data.snapshot) {
          await db.notes.bulkPut(data.snapshot.notes);
          await db.meta.put({ key: 'last_revision', value: data.latestRevision });
        }
      }
    } catch (err) {
      console.error('Snapshot fetch error', err);
    }
  }
}

export const syncEngine = new SyncEngine();
